apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kpt-test-deployment
  name: kpt-test-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kpt-test-deployment
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kpt-test-deployment
    spec:
      containers:
      - name: kpt-test-deployment
        image: us-central1-docker.pkg.dev/searce-playground-v1/kpt-test-repo/kpt-image:tag
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "32Mi"
            cpu: "1m"
          limits:
            memory: "256Mi"
            cpu: "100m"

